import type { Metadata } from "next";
import { Inter, Merriweather_Sans } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/shared/Navbar";
// const inter = Inter({ subsets: ["latin"] });
const merriWeather = Merriweather_Sans({
  weight: ["400", "700", "800"],
  subsets: ["vietnamese"],
});

export const metadata: Metadata = {
  title: "ArtLink",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={merriWeather.className} suppressHydrationWarning={true}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
