import type { Metadata } from "next";
import { Inter, Merriweather_Sans } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/shared/Navbar";
import { SessionProvider, useSession } from "next-auth/react";
import { auth } from "@/auth";
// const inter = Inter({ subsets: ["latin"] });
const merriWeather = Merriweather_Sans({
  weight: ["400", "700", "800"],
  subsets: ["vietnamese"],
});

export const metadata: Metadata = {
  title: "ArtLink",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();

  return (
    <SessionProvider session={session}>
      <html lang="en">
        <body
          className={merriWeather.className}
          suppressHydrationWarning={true}
        >
          <Navbar />
          {children}
        </body>
      </html>
    </SessionProvider>
  );
}
